# Generated by Django 4.1.2 on 2022-10-22 09:05

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Сумма')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата утсановления статуса')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения статуса')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Имя')),
                ('description', models.CharField(max_length=125)),
                ('cover', models.ImageField(upload_to='media/images', verbose_name='Главное фото')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Данный товар активен')),
                ('brands', models.ManyToManyField(related_name='products', to='app.brand', verbose_name='Бренды')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.SmallIntegerField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], verbose_name='Размер')),
                ('color', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None, verbose_name='Цвет')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата нового поступления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена товара')),
                ('start_date', models.DateTimeField(verbose_name='Дата старта цены')),
                ('end_date', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 12, 0, 59), verbose_name='Дата конца цены')),
                ('is_actual', models.BooleanField(default=False, verbose_name='Актуальная цена')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Продукт')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='app.order', verbose_name='Заказ')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='app.stock', verbose_name='Склад')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='app.stock', verbose_name='Склад'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='DetailPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images', verbose_name='Детальное фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Продукты')),
            ],
        ),
    ]
