# Generated by Django 4.1.2 on 2022-10-24 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_price_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='active',
        ),
    ]
