# Generated by Django 4.1.2 on 2022-10-24 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_is_active_product_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='is_actual',
            new_name='is_active',
        ),
    ]
