# Generated by Django 4.1.2 on 2022-10-24 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_link_alter_brand_options_alter_detailphotos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailphotos',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='app.product', verbose_name='Продукты'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='app.product', verbose_name='Продукт'),
        ),
    ]
