# Generated by Django 4.1.2 on 2022-10-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_detailphotos_product_alter_stock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brands',
            new_name='brand',
        ),
    ]
