# Generated by Django 4.1.2 on 2022-10-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_brands_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
    ]
